class HelpTexts {
  static const String home = 
      "ホーム画面では、以下の操作が可能です:\n\n"
      "1. おすすめ商品の確認:\n"
      "   - 出品中のおすすめ商品がランダムに5つ表示されます。\n"
      "   - 商品カードをタップすると、商品の詳細ページに移動します。\n\n"
      "2. 商品詳細の確認:\n"
      "   - 詳細ページでは、商品の説明、価格、出品者情報を確認できます。\n"
      "   - 「購入する」ボタンを押すと、購入手続き画面に進みます。\n\n"
      "3. 購入手続き:\n"
      "   - 来店予定日または配送希望日を選択し、契約書に同意する必要があります。\n"
      "   - 配送を選択した場合、メールアドレス、本名、住所、電話番号が必要です。\n"
      "   - 購入が完了すると、来店予定が追加され、商品は「購入済み」としてマークされます。\n\n"
      "4. その他の操作:\n"
      "   - 右上のハートアイコンを押すと、お気に入り商品一覧ページに移動します。\n"
      "   - 「すべての商品を見る」ボタンを押すと、カタログページに移動してすべての商品を確認できます。\n\n"
      "The Home screen allows the following actions:\n\n"
      "1. Viewing recommended products:\n"
      "   - A random selection of 5 recommended products currently listed for sale is displayed.\n"
      "   - Tapping on a product card navigates to the product details page.\n\n"
      "2. Viewing product details:\n"
      "   - On the details page, you can view the product description, price, and seller information.\n"
      "   - Pressing the 'Purchase' button takes you to the purchase process screen.\n\n"
      "3. Purchase process:\n"
      "   - You need to select a visit date or desired delivery date and agree to the sales agreement.\n"
      "   - If delivery is selected, an email address, full name, address, and phone number are required.\n"
      "   - Once the purchase is completed, a visit schedule is added, and the product is marked as 'Purchased.'\n\n"
      "4. Other actions:\n"
      "   - Clicking the heart icon in the top-right corner takes you to the favorites list page.\n"
      "   - Pressing the 'View All Products' button navigates to the catalog page to see all products.";

  static const String shop = 
      "ショップ画面では、以下の操作が可能です:\n\n"
      "1. 商品の出品:\n"
      "   - 「出品する」ボタンを押すと、商品を出品する画面に移動します。\n"
      "   - 商品名、説明、価格、カテゴリ、画像、来店予定日などを入力し、同意書に同意することで商品を出品できます。\n"
      "   - 画像は最大5枚までアップロード可能で、並び替えや削除もできます。\n"
      "   - 商品を下書きとして保存し、後で編集することも可能です。\n\n"
      "2. 来店予定リストの確認:\n"
      "   - 自分の予定を確認できます。\n"
      "   - リストには、商品名、来店予定日、受け取り方法（店舗受け取りまたは配送）が表示されます。\n"
      "   - 商品をタップすると、詳細画面に移動します。\n\n"
      "3. 商品詳細の確認と購入:\n"
      "   - 詳細画面では、商品の説明、価格、カテゴリ、画像、出品者情報、出品日時などを確認できます。\n"
      "   - 購入ボタンを押すと、購入手続き画面に進みます。\n"
      "   - 購入手続きでは、来店予定日または配送希望日を選択し、契約書に同意する必要があります。\n"
      "   - 配送を選択した場合、メールアドレス、本名、住所、電話番号が必要です。\n"
      "   - 購入が完了すると、来店予定が追加され、商品は「購入済み」としてマークされます。\n"
      "   - 購入済みの商品はキャンセル手続きが可能です。\n\n"
      "The Shop screen allows the following actions:\n\n"
      "1. Listing products:\n"
      "   - Pressing the 'List' button navigates to the product listing screen.\n"
      "   - Users can input product details such as name, description, price, category, images, and visit date.\n"
      "   - Users must agree to the sales agreement to list a product.\n"
      "   - Images can be uploaded (up to 5), reordered, or deleted.\n"
      "   - Products can be saved as drafts and edited later.\n\n"
      "2. Viewing visit schedules:\n"
      "   - Users can check their schedules.\n"
      "   - The list shows product names, scheduled visit dates, and pickup methods (store pickup or delivery).\n"
      "   - Tapping on a product navigates to the detail screen.\n\n"
      "3. Viewing product details and purchasing:\n"
      "   - On the detail screen, users can view product descriptions, prices, categories, images, seller information, and listing dates.\n"
      "   - Pressing the purchase button navigates to the purchase process screen.\n"
      "   - In the purchase process, users must select a visit date or desired delivery date and agree to the sales agreement.\n"
      "   - If delivery is selected, an email address, full name, address, and phone number are required.\n"
      "   - Once the purchase is completed, a visit schedule is added, and the product is marked as 'Purchased.'\n"
      "   - Purchased products can also be canceled.";

  static const String user = 
      "ユーザー画面では、以下の操作が可能です:\n\n"
      "1. プロフィール情報の確認と編集:\n"
      "   - プロフィール画面では、ユーザー名、メールアドレス、写真、本名、住所、電話番号などの情報を確認できます。\n"
      "   - 「プロフィール編集」ボタンを押すと、これらの情報を編集する画面に移動します。\n"
      "   - プロフィール写真は新しい画像をアップロードして変更可能です。\n\n"
      "2. ユーザー詳細の確認:\n"
      "   - 「ユーザー情報」ボタンを押すと、詳細情報を確認できます。\n"
      "   - 詳細情報には、UID（ユーザーID）や登録された本名、住所、電話番号などが含まれます。\n\n"
      "3. お気に入り商品の確認:\n"
      "   - 「いいねした商品一覧」ボタンを押すと、お気に入りに登録した商品の一覧ページに移動します。\n"
      "   - お気に入り商品は、詳細ページから追加または削除できます。\n\n"
      "4. ログアウト:\n"
      "   - 「ログアウト」ボタンを押すと、現在のアカウントからログアウトします。\n"
      "   - ログアウト後は、ログイン画面にリダイレクトされます。\n\n"
      "The User screen allows the following actions:\n\n"
      "1. Viewing and editing profile information:\n"
      "   - On the profile screen, you can view details such as username, email, photo, full name, address, and phone number.\n"
      "   - Pressing the 'Edit Profile' button navigates to a screen where you can update this information.\n"
      "   - Profile photos can be updated by uploading a new image.\n\n"
      "2. Viewing user details:\n"
      "   - Pressing the 'User Details' button displays detailed information.\n"
      "   - This includes UID (User ID), registered full name, address, and phone number.\n\n"
      "3. Viewing favorite items:\n"
      "   - Pressing the 'Favorite Items List' button navigates to a page displaying your favorited products.\n"
      "   - Favorite items can be added or removed from their respective detail pages.\n\n"
      "4. Logging out:\n"
      "   - Pressing the 'Logout' button logs you out of the current account.\n"
      "   - After logging out, you will be redirected to the login screen.";
}
