// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLkDgCEwNilX_QBggTK_w3nSatQrRpQDQ',
    appId: '1:184044888801:web:b52c7213b17daac0ddcda0',
    messagingSenderId: '184044888801',
    projectId: 'apushion',
    authDomain: 'apushion.firebaseapp.com',
    storageBucket: 'apushion.firebasestorage.app',
    measurementId: 'G-D95YS1NXSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH65jGrsnQl47JyywOJf_t4G_zevOJ36s',
    appId: '1:184044888801:android:b5bed61d5450690eddcda0',
    messagingSenderId: '184044888801',
    projectId: 'apushion',
    storageBucket: 'apushion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoovwOY6IezJZ1KAytU0umFG9Dlo_Gjnc',
    appId: '1:184044888801:ios:af4ecd012cf8ad3cddcda0',
    messagingSenderId: '184044888801',
    projectId: 'apushion',
    storageBucket: 'apushion.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoovwOY6IezJZ1KAytU0umFG9Dlo_Gjnc',
    appId: '1:184044888801:ios:af4ecd012cf8ad3cddcda0',
    messagingSenderId: '184044888801',
    projectId: 'apushion',
    storageBucket: 'apushion.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLkDgCEwNilX_QBggTK_w3nSatQrRpQDQ',
    appId: '1:184044888801:web:3708dca88682396dddcda0',
    messagingSenderId: '184044888801',
    projectId: 'apushion',
    authDomain: 'apushion.firebaseapp.com',
    storageBucket: 'apushion.firebasestorage.app',
    measurementId: 'G-KEQJF6KVDB',
  );
}
